"""2

Revision ID: 25346ea77641
Revises: f0ff1f0c93fa
Create Date: 2023-09-11 14:31:40.391765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25346ea77641'
down_revision = 'f0ff1f0c93fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt',
    sa.Column('receipt_number', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=9, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['point_id'], ['shop.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id_warehouse'], ),
    sa.PrimaryKeyConstraint('receipt_number', 'product_id', name='receipt')
    )
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipt_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipt_date'))

    op.drop_table('receipt')
    # ### end Alembic commands ###
