"""1

Revision ID: f0ff1f0c93fa
Revises: 
Create Date: 2023-09-11 11:41:11.505271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ff1f0c93fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_id_warehouse', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=64), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=9, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('product_id_warehouse')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_product'), ['product'], unique=True)

    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_address'), ['address'], unique=True)

    op.create_table('deliveries',
    sa.Column('deliveries_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('deliveries_date', sa.DateTime(), nullable=True),
    sa.Column('deliveries_price', sa.NUMERIC(precision=9, scale=2), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('stock_availability', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['point_id'], ['shop.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id_warehouse'], ),
    sa.PrimaryKeyConstraint('deliveries_id')
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_deliveries_date'), ['deliveries_date'], unique=False)

    op.create_table('expenses',
    sa.Column('expenses_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('rent', sa.NUMERIC(precision=9, scale=2), nullable=False),
    sa.Column('services', sa.NUMERIC(precision=9, scale=2), nullable=False),
    sa.Column('salary', sa.NUMERIC(precision=9, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['point_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('expenses_id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_date'))

    op.drop_table('expenses')
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_deliveries_date'))

    op.drop_table('deliveries')
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_address'))

    op.drop_table('shop')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_product'))

    op.drop_table('product')
    # ### end Alembic commands ###
